import type { Article, Author, Tag } from '@/types';

export const MOCK_AUTHOR: Author = {
  id: '1',
  name: 'Alex Chen',
  avatar: 'https://ui-avatars.com/api/?name=Alex+Chen&background=6366f1&color=fff&size=256',
  bio: 'Senior Software Engineer with 8+ years of experience building distributed systems. Passionate about clean architecture, performance, and teaching complex concepts simply.',
  github: 'https://github.com/alexchen',
  twitter: 'https://twitter.com/alexchen',
  linkedin: 'https://linkedin.com/in/alexchen',
};

export const MOCK_TAGS: Tag[] = [
  { id: '1', slug: 'java', name: 'Java', articleCount: 18 },
  { id: '2', slug: 'spring-boot', name: 'Spring Boot', articleCount: 14 },
  { id: '3', slug: 'microservices', name: 'Microservices', articleCount: 12 },
  { id: '4', slug: 'kafka', name: 'Kafka', articleCount: 9 },
  { id: '5', slug: 'system-design', name: 'System Design', articleCount: 15 },
  { id: '6', slug: 'docker', name: 'Docker', articleCount: 10 },
  { id: '7', slug: 'kubernetes', name: 'Kubernetes', articleCount: 8 },
  { id: '8', slug: 'ai', name: 'AI', articleCount: 16 },
  { id: '9', slug: 'machine-learning', name: 'Machine Learning', articleCount: 13 },
  { id: '10', slug: 'llm', name: 'LLM', articleCount: 11 },
  { id: '11', slug: 'databases', name: 'Databases', articleCount: 12 },
  { id: '12', slug: 'postgresql', name: 'PostgreSQL', articleCount: 7 },
  { id: '13', slug: 'redis', name: 'Redis', articleCount: 8 },
  { id: '14', slug: 'design-patterns', name: 'Design Patterns', articleCount: 14 },
  { id: '15', slug: 'clean-code', name: 'Clean Code', articleCount: 10 },
  { id: '16', slug: 'interview', name: 'Interview', articleCount: 20 },
  { id: '17', slug: 'career', name: 'Career', articleCount: 9 },
  { id: '18', slug: 'productivity', name: 'Productivity', articleCount: 7 },
  { id: '19', slug: 'python', name: 'Python', articleCount: 8 },
  { id: '20', slug: 'rest-api', name: 'REST API', articleCount: 11 },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    slug: 'getting-started-with-spring-boot',
    title: 'Getting Started with Spring Boot: A Complete Guide for 2025',
    description:
      'Learn how to build production-ready REST APIs with Spring Boot 3.x, including auto-configuration, dependency injection, JPA, and best practices for enterprise applications.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    category: 'Spring Boot',
    categorySlug: 'spring-boot',
    tags: ['java', 'spring-boot', 'rest-api', 'microservices'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-01-15T10:00:00Z',
    readingTime: 12,
    featured: true,
    views: 8420,
    tableOfContents: [
      { id: 'introduction', title: 'Introduction', level: 2 },
      { id: 'setup', title: 'Project Setup', level: 2 },
      { id: 'auto-configuration', title: 'Auto-Configuration', level: 2 },
      { id: 'rest-controller', title: 'Building REST Controllers', level: 2 },
      { id: 'jpa', title: 'Working with JPA', level: 2 },
      { id: 'best-practices', title: 'Best Practices', level: 2 },
    ],
  },
  {
    id: '2',
    slug: 'kafka-fundamentals-event-driven',
    title: 'Apache Kafka Fundamentals: Building Event-Driven Architectures',
    description:
      'A deep dive into Apache Kafka — topics, partitions, consumer groups, offset management, and how to build resilient event-driven systems at scale.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    category: 'Kafka',
    categorySlug: 'kafka',
    tags: ['kafka', 'microservices', 'system-design', 'java'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-01-22T10:00:00Z',
    readingTime: 15,
    featured: true,
    views: 6200,
    tableOfContents: [
      { id: 'what-is-kafka', title: 'What is Apache Kafka?', level: 2 },
      { id: 'core-concepts', title: 'Core Concepts', level: 2 },
      { id: 'topics-partitions', title: 'Topics & Partitions', level: 3 },
      { id: 'producers-consumers', title: 'Producers & Consumers', level: 3 },
      { id: 'consumer-groups', title: 'Consumer Groups', level: 3 },
      { id: 'spring-kafka', title: 'Spring Kafka Integration', level: 2 },
      { id: 'best-practices', title: 'Production Best Practices', level: 2 },
    ],
  },
  {
    id: '3',
    slug: 'system-design-fundamentals',
    title: 'System Design Fundamentals: Scalability, Reliability & Performance',
    description:
      'Master the core principles of system design — load balancing, caching, database sharding, CAP theorem, and how to design systems that serve millions of users.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    category: 'System Design',
    categorySlug: 'system-design',
    tags: ['system-design', 'databases', 'microservices', 'career'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-02-01T10:00:00Z',
    readingTime: 18,
    featured: true,
    views: 12100,
    tableOfContents: [
      { id: 'scalability', title: 'Scalability Fundamentals', level: 2 },
      { id: 'load-balancing', title: 'Load Balancing', level: 2 },
      { id: 'caching', title: 'Caching Strategies', level: 2 },
      { id: 'database-design', title: 'Database Design', level: 2 },
      { id: 'cap-theorem', title: 'CAP Theorem', level: 2 },
      { id: 'case-studies', title: 'Real-World Case Studies', level: 2 },
    ],
  },
  {
    id: '4',
    slug: 'microservices-patterns-production',
    title: 'Microservices Patterns You Need to Know for Production',
    description:
      'Explore battle-tested microservices patterns: Circuit Breaker, Saga, Event Sourcing, CQRS, and API Gateway — with real implementation examples in Java.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    category: 'Microservices',
    categorySlug: 'microservices',
    tags: ['microservices', 'design-patterns', 'java', 'system-design'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-02-10T10:00:00Z',
    readingTime: 20,
    featured: false,
    views: 7800,
    tableOfContents: [
      { id: 'circuit-breaker', title: 'Circuit Breaker Pattern', level: 2 },
      { id: 'saga', title: 'Saga Pattern', level: 2 },
      { id: 'event-sourcing', title: 'Event Sourcing', level: 2 },
      { id: 'cqrs', title: 'CQRS', level: 2 },
      { id: 'api-gateway', title: 'API Gateway', level: 2 },
    ],
  },
  {
    id: '5',
    slug: 'java-concurrency-deep-dive',
    title: 'Java Concurrency Deep Dive: Threads, Locks, and Virtual Threads',
    description:
      'A comprehensive guide to Java concurrency — the Java Memory Model, synchronized blocks, ReentrantLock, CompletableFuture, and Java 21 virtual threads.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800&q=80',
    category: 'Java',
    categorySlug: 'java',
    tags: ['java', 'concurrency', 'performance', 'clean-code'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-02-18T10:00:00Z',
    readingTime: 22,
    featured: false,
    views: 5900,
    tableOfContents: [
      { id: 'java-memory-model', title: 'Java Memory Model', level: 2 },
      { id: 'threads', title: 'Threads & Synchronization', level: 2 },
      { id: 'locks', title: 'Locks & Conditions', level: 2 },
      { id: 'completable-future', title: 'CompletableFuture', level: 2 },
      { id: 'virtual-threads', title: 'Virtual Threads (Java 21)', level: 2 },
    ],
  },
  {
    id: '6',
    slug: 'llm-fine-tuning-guide',
    title: 'Fine-Tuning LLMs: From Theory to Production',
    description:
      'Learn how to fine-tune large language models using LoRA, QLoRA, and instruction tuning. Covers dataset preparation, training, evaluation, and deployment.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    category: 'Artificial Intelligence',
    categorySlug: 'artificial-intelligence',
    tags: ['ai', 'llm', 'machine-learning', 'python'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-03-01T10:00:00Z',
    readingTime: 25,
    featured: true,
    views: 15300,
    tableOfContents: [
      { id: 'what-is-fine-tuning', title: 'What is Fine-Tuning?', level: 2 },
      { id: 'lora', title: 'LoRA & QLoRA', level: 2 },
      { id: 'dataset-prep', title: 'Dataset Preparation', level: 2 },
      { id: 'training', title: 'Training Pipeline', level: 2 },
      { id: 'evaluation', title: 'Evaluation Metrics', level: 2 },
      { id: 'deployment', title: 'Deployment Strategies', level: 2 },
    ],
  },
  {
    id: '7',
    slug: 'postgresql-performance-tuning',
    title: 'PostgreSQL Performance Tuning: Indexes, Query Plans & Partitioning',
    description:
      'Master PostgreSQL performance optimization — B-tree indexes, partial indexes, EXPLAIN ANALYZE, vacuum, partitioning, and connection pooling with PgBouncer.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
    category: 'Databases',
    categorySlug: 'databases',
    tags: ['databases', 'postgresql', 'performance', 'system-design'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-03-10T10:00:00Z',
    readingTime: 16,
    featured: false,
    views: 4600,
  },
  {
    id: '8',
    slug: 'docker-kubernetes-essentials',
    title: 'Docker & Kubernetes Essentials for Backend Developers',
    description:
      'Everything you need to deploy containerized applications — Dockerfiles, multi-stage builds, Kubernetes deployments, services, ingress, and Helm charts.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800&q=80',
    category: 'Technical',
    categorySlug: 'technical',
    tags: ['docker', 'kubernetes', 'microservices', 'system-design'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-03-18T10:00:00Z',
    readingTime: 19,
    featured: false,
    views: 6800,
  },
  {
    id: '9',
    slug: 'system-design-interview-prep',
    title: 'Cracking the System Design Interview: A Complete Framework',
    description:
      'A step-by-step framework for answering system design interview questions. Covers requirement clarification, capacity estimation, high-level design, and deep dives.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80',
    category: 'Interview Preparation',
    categorySlug: 'interview-preparation',
    tags: ['interview', 'system-design', 'career'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-03-25T10:00:00Z',
    readingTime: 30,
    featured: true,
    views: 19400,
  },
  {
    id: '10',
    slug: 'clean-code-principles',
    title: 'Clean Code Principles Every Engineer Should Master',
    description:
      'A practical guide to writing clean, maintainable code — meaningful names, small functions, SOLID principles, refactoring techniques, and code review best practices.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&q=80',
    category: 'Technical',
    categorySlug: 'technical',
    tags: ['clean-code', 'design-patterns', 'career', 'java'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-04-05T10:00:00Z',
    readingTime: 14,
    featured: false,
    views: 5200,
  },
  {
    id: '11',
    slug: 'rag-applications-langchain',
    title: 'Building RAG Applications with LangChain and Vector Databases',
    description:
      'End-to-end guide to building Retrieval-Augmented Generation apps — document ingestion, embeddings, vector stores, and building context-aware AI assistants.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    category: 'Artificial Intelligence',
    categorySlug: 'artificial-intelligence',
    tags: ['ai', 'llm', 'python', 'machine-learning'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-04-15T10:00:00Z',
    readingTime: 21,
    featured: false,
    views: 9100,
  },
  {
    id: '12',
    slug: 'growth-mindset-engineers',
    title: 'The Growth Mindset for Software Engineers: Learning at Scale',
    description:
      'How to stay relevant in a fast-moving industry — deliberate practice, learning frameworks, dealing with imposter syndrome, and building a personal knowledge system.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    category: 'Psychology',
    categorySlug: 'psychology',
    tags: ['productivity', 'career', 'interview'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-04-22T10:00:00Z',
    readingTime: 10,
    featured: false,
    views: 3800,
  },
  {
    id: '13',
    slug: 'redis-caching-strategies',
    title: 'Redis Caching Strategies: From Basics to Advanced Patterns',
    description:
      'Comprehensive guide to Redis — data structures, caching patterns (Cache-Aside, Write-Through, Write-Behind), TTL strategies, and distributed locking.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    category: 'Databases',
    categorySlug: 'databases',
    tags: ['redis', 'databases', 'system-design', 'performance'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-05-01T10:00:00Z',
    readingTime: 13,
    featured: false,
    views: 4400,
  },
  {
    id: '14',
    slug: 'behavioral-interview-guide',
    title: 'The Complete Behavioral Interview Guide for Engineers',
    description:
      'Master the STAR method, prepare compelling stories, and answer the 30 most common behavioral interview questions for software engineering roles.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
    category: 'Interview Preparation',
    categorySlug: 'interview-preparation',
    tags: ['interview', 'career', 'productivity'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-05-10T10:00:00Z',
    readingTime: 17,
    featured: false,
    views: 7600,
  },
  {
    id: '15',
    slug: 'design-patterns-java',
    title: 'GoF Design Patterns in Java: Practical Examples',
    description:
      'All 23 Gang of Four design patterns explained with real-world Java examples — creational, structural, and behavioral patterns with pros, cons, and when to use them.',
    content: '',
    thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&q=80',
    category: 'Low Level Design',
    categorySlug: 'low-level-design',
    tags: ['design-patterns', 'java', 'clean-code', 'interview'],
    author: MOCK_AUTHOR,
    publishedAt: '2025-05-20T10:00:00Z',
    readingTime: 28,
    featured: false,
    views: 8900,
  },
];
