import type { Category } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: '1',
    slug: 'technical',
    name: 'Technical',
    description: 'Deep dives into software engineering concepts, best practices, and hands-on tutorials.',
    icon: '💻',
    color: '#6366f1',
    articleCount: 24,
    featured: true,
  },
  {
    id: '2',
    slug: 'artificial-intelligence',
    name: 'Artificial Intelligence',
    description: 'Exploring machine learning, deep learning, LLMs, and practical AI applications.',
    icon: '🤖',
    color: '#8b5cf6',
    articleCount: 18,
    featured: true,
  },
  {
    id: '3',
    slug: 'system-design',
    name: 'System Design',
    description: 'Scalable architecture patterns, distributed systems, and design principles.',
    icon: '🏗️',
    color: '#0ea5e9',
    articleCount: 15,
    featured: true,
  },
  {
    id: '4',
    slug: 'low-level-design',
    name: 'Low Level Design',
    description: 'Object-oriented design, design patterns, and clean code principles.',
    icon: '🔧',
    color: '#f59e0b',
    articleCount: 12,
  },
  {
    id: '5',
    slug: 'java',
    name: 'Java',
    description: 'Java fundamentals, advanced features, JVM internals, and performance tuning.',
    icon: '☕',
    color: '#ef4444',
    articleCount: 20,
    featured: true,
  },
  {
    id: '6',
    slug: 'spring-boot',
    name: 'Spring Boot',
    description: 'Building production-grade Spring Boot applications, REST APIs, and more.',
    icon: '🌱',
    color: '#22c55e',
    articleCount: 16,
  },
  {
    id: '7',
    slug: 'microservices',
    name: 'Microservices',
    description: 'Microservices architecture, patterns, service mesh, and orchestration.',
    icon: '🔗',
    color: '#14b8a6',
    articleCount: 14,
  },
  {
    id: '8',
    slug: 'kafka',
    name: 'Kafka',
    description: 'Event-driven architecture, Apache Kafka, message queues, and stream processing.',
    icon: '⚡',
    color: '#f97316',
    articleCount: 10,
  },
  {
    id: '9',
    slug: 'databases',
    name: 'Databases',
    description: 'SQL, NoSQL, database design, query optimization, and data modeling.',
    icon: '🗄️',
    color: '#06b6d4',
    articleCount: 13,
  },
  {
    id: '10',
    slug: 'psychology',
    name: 'Psychology',
    description: 'Cognitive science, productivity, focus, and the psychology of learning.',
    icon: '🧠',
    color: '#ec4899',
    articleCount: 8,
    featured: true,
  },
  {
    id: '11',
    slug: 'interview-preparation',
    name: 'Interview Preparation',
    description: 'DSA, system design interviews, behavioral questions, and career tips.',
    icon: '🎯',
    color: '#a855f7',
    articleCount: 22,
    featured: true,
  },
  {
    id: '12',
    slug: 'career',
    name: 'Career',
    description: 'Career growth, leadership, mentoring, and navigating the tech industry.',
    icon: '🚀',
    color: '#64748b',
    articleCount: 9,
  },
  {
    id: '13',
    slug: 'projects',
    name: 'Projects',
    description: 'Real-world project walkthroughs, case studies, and open source contributions.',
    icon: '🛠️',
    color: '#84cc16',
    articleCount: 7,
  },
];
